modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "chestseparators"
version = "${version}"
displayName = "Absolute Order"
authors = "marcsanz-dev"
logoFile = "icon.png"
description = '''
Custom chest auto-sorter with visual separators and per-slot filters.
'''

[[dependencies.chestseparators]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestseparators]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestseparators]]
modId = "cloth_config"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.chestseparators]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "absoluteorder.mixins.json"

[[mixins]]
config = "absoluteorder-forge.mixins.json"
