package io.github.marcsanzdev.chestseparators.mixin;

import io.github.marcsanzdev.chestseparators.access.IShulkerUUIDProvider;
import io.github.marcsanzdev.chestseparators.access.IWhitelistProvider;
import io.github.marcsanzdev.chestseparators.data.SlotWhitelist;
import io.github.marcsanzdev.chestseparators.registry.ChestSeparatorsComponents;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.entity.BarrelBlockEntity;
import net.minecraft.block.entity.BlockEntity;
import net.minecraft.block.entity.ChestBlockEntity;
import net.minecraft.entity.Entity;
import net.minecraft.item.BlockItem;
import net.minecraft.item.ItemStack;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.math.BlockPos;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Intercepts block dropping logic to attach custom components to the dropped items.
 */
@Mixin(Block.class)
public abstract class BlockDropMixin {

    @Inject(method = "getDroppedStacks(Lnet/minecraft/block/BlockState;Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/entity/BlockEntity;)Ljava/util/List;", at = @At("RETURN"))
    private static void onGetDroppedStacks(BlockState state, ServerWorld world, BlockPos pos, BlockEntity blockEntity, CallbackInfoReturnable<List<ItemStack>> cir) {
        injectDataToDrops(blockEntity, cir.getReturnValue());
    }

    @Inject(method = "getDroppedStacks(Lnet/minecraft/block/BlockState;Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/entity/BlockEntity;Lnet/minecraft/entity/Entity;Lnet/minecraft/item/ItemStack;)Ljava/util/List;", at = @At("RETURN"))
    private static void onGetDroppedStacksWithEntity(BlockState state, ServerWorld world, BlockPos pos, BlockEntity blockEntity, Entity entity, ItemStack tool, CallbackInfoReturnable<List<ItemStack>> cir) {
        injectDataToDrops(blockEntity, cir.getReturnValue());
    }

    /**
     * Injects custom component data (UUIDs and Whitelists) into the generated item drops.
     *
     * @param blockEntity The block entity being broken.
     * @param drops       The list of ItemStacks generated by the block drop event.
     */
    private static void injectDataToDrops(BlockEntity blockEntity, List<ItemStack> drops) {
        if (blockEntity == null || drops == null || drops.isEmpty()) return;

        for (ItemStack drop : drops) {
            // Check that the drop is actually the block itself
            if (drop.getItem() instanceof BlockItem) {
                if (blockEntity instanceof IShulkerUUIDProvider provider) {
                    UUID uuid = provider.getShulkerUUID();
                    if (uuid != null) {
                        drop.set(ChestSeparatorsComponents.SHULKER_UUID, uuid);
                    }
                }

                if (blockEntity instanceof IWhitelistProvider provider) {
                    // EXCLUSION: Do not save whitelists to the dropped item if it is a standard Chest or Barrel
                    boolean isStandardChest = blockEntity instanceof ChestBlockEntity || blockEntity instanceof BarrelBlockEntity;

                    if (!isStandardChest) {
                        Map<Integer, SlotWhitelist> whitelists = provider.getWhitelists();
                        if (whitelists != null && !whitelists.isEmpty()) {
                            drop.set(ChestSeparatorsComponents.SLOT_WHITELISTS, new HashMap<>(whitelists));
                        }
                    }
                }
            }
        }
    }
}